/**
 * Single source of truth for MRT station lists.
 *
 * Previously `Map.tsx:MRT_LINE_STATIONS` (display, incl. future lines) and
 * `mrt-routing.ts:MRT_OPERATIONAL_LINE_STATIONS` (routeable only) were
 * maintained independently — a station rename in one silently desynced the
 * other. Both now import from here.
 *
 * - `MRT_OPERATIONAL_LINE_STATIONS`: routeable network used by Dijkstra.
 * - `MRT_DISPLAY_LINE_STATIONS`: full network for the map, including future
 *   / non-routeable extensions. Operational lines reference the same arrays
 *   so they can never drift.
 */

export const MRT_OPERATIONAL_LINE_STATIONS: Record<string, string[]> = {
  "North South Line": [
    "Jurong East",
    "Bukit Batok",
    "Bukit Gombak",
    "Choa Chu Kang",
    "Yew Tee",
    "Kranji",
    "Marsiling",
    "Woodlands",
    "Admiralty",
    "Sembawang",
    "Canberra",
    "Yishun",
    "Khatib",
    "Yio Chu Kang",
    "Ang Mo Kio",
    "Bishan",
    "Braddell",
    "Toa Payoh",
    "Novena",
    "Newton",
    "Orchard",
    "Somerset",
    "Dhoby Ghaut",
    "City Hall",
    "Raffles Place",
    "Marina Bay",
    "Marina South Pier",
  ],
  "East West Line": [
    "Tuas Link",
    "Tuas West Road",
    "Tuas Crescent",
    "Gul Circle",
    "Joo Koon",
    "Pioneer",
    "Boon Lay",
    "Lakeside",
    "Chinese Garden",
    "Jurong East",
    "Clementi",
    "Dover",
    "Buona Vista",
    "Commonwealth",
    "Queenstown",
    "Redhill",
    "Tiong Bahru",
    "Outram Park",
    "Tanjong Pagar",
    "Raffles Place",
    "City Hall",
    "Bugis",
    "Lavender",
    "Kallang",
    "Aljunied",
    "Paya Lebar",
    "Eunos",
    "Kembangan",
    "Bedok",
    "Tanah Merah",
    "Simei",
    "Tampines",
    "Pasir Ris",
  ],
  "Changi Airport Branch": ["Tanah Merah", "Expo", "Changi Airport"],
  "North East Line": [
    "HarbourFront",
    "Outram Park",
    "Chinatown",
    "Clarke Quay",
    "Dhoby Ghaut",
    "Little India",
    "Farrer Park",
    "Boon Keng",
    "Potong Pasir",
    "Woodleigh",
    "Serangoon",
    "Kovan",
    "Hougang",
    "Buangkok",
    "Sengkang",
    "Punggol",
    "Punggol Coast",
  ],
  "Circle Line": [
    "Dhoby Ghaut",
    "Bras Basah",
    "Esplanade",
    "Promenade",
    "Nicoll Highway",
    "Stadium",
    "Mountbatten",
    "Dakota",
    "Paya Lebar",
    "MacPherson",
    "Tai Seng",
    "Bartley",
    "Serangoon",
    "Lorong Chuan",
    "Bishan",
    "Marymount",
    "Caldecott",
    "Botanic Gardens",
    "Farrer Road",
    "Holland Village",
    "Buona Vista",
    "one-north",
    "Kent Ridge",
    "Haw Par Villa",
    "Pasir Panjang",
    "Labrador Park",
    "Telok Blangah",
    "HarbourFront",
  ],
  "Circle Line Extension": [
    "HarbourFront",
    "Keppel",
    "Cantonment",
    "Prince Edward Road",
    "Marina Bay",
  ],
  "Downtown Line": [
    "Bukit Panjang",
    "Cashew",
    "Hillview",
    "Beauty World",
    "King Albert Park",
    "Sixth Avenue",
    "Tan Kah Kee",
    "Botanic Gardens",
    "Stevens",
    "Newton",
    "Little India",
    "Rochor",
    "Bugis",
    "Promenade",
    "Bayfront",
    "Downtown",
    "Telok Ayer",
    "Chinatown",
    "Fort Canning",
    "Bencoolen",
    "Jalan Besar",
    "Bendemeer",
    "Geylang Bahru",
    "Mattar",
    "MacPherson",
    "Ubi",
    "Kaki Bukit",
    "Bedok North",
    "Bedok Reservoir",
    "Tampines West",
    "Tampines",
    "Tampines East",
    "Upper Changi",
    "Expo",
  ],
  // TEL operational: Woodlands North → Bayshore. TEL Stage 5
  // (Bedok South, Sungei Bedok) is planned, NOT operational.
  "Thomson-East Coast Line": [
    "Woodlands North",
    "Woodlands",
    "Woodlands South",
    "Springleaf",
    "Lentor",
    "Mayflower",
    "Bright Hill",
    "Upper Thomson",
    "Caldecott",
    "Stevens",
    "Napier",
    "Orchard Boulevard",
    "Orchard",
    "Great World",
    "Havelock",
    "Outram Park",
    "Maxwell",
    "Shenton Way",
    "Marina Bay",
    "Gardens by the Bay",
    "Tanjong Rhu",
    "Katong Park",
    "Tanjong Katong",
    "Marine Parade",
    "Marine Terrace",
    "Siglap",
    "Bayshore",
  ],
};

/** Future / non-routeable extensions shown on the map only. */
const MRT_FUTURE_LINE_STATIONS: Record<string, string[]> = {
  // TEL Stage 5 extension — planned 2H 2026, NOT yet operational.
  "Thomson-East Coast Line Extension": [
    "Bayshore",
    "Bedok South",
    "Sungei Bedok",
  ],
  "Jurong Region Line": [
    "Choa Chu Kang",
    "Choa Chu Kang West",
    "JS2A",
    "Tengah",
    "Hong Kah",
    "Corporation",
    "Jurong West",
    "Bahar Junction",
    "Boon Lay",
    "Enterprise",
    "Tukang",
    "Jurong Hill",
    "Jurong Pier",
  ],
  "Jurong Region Line West Branch": [
    "Bahar Junction",
    "Gek Poh",
    "Tawas",
    "Nanyang Gateway",
    "Nanyang Crescent",
    "Peng Kang Hill",
  ],
  "Jurong Region Line East Branch": [
    "Tengah",
    "Tengah Plantation",
    "Tengah Park",
    "Bukit Batok West",
    "Toh Guan",
    "Jurong East",
    "Jurong Town Hall",
    "Pandan Reservoir",
  ],
  // WCE: Pandan Reservoir (JE7) -> West Coast -> Kent Ridge; late 2030s.
  "Jurong Region Line West Coast Extension": [
    "Pandan Reservoir",
    "West Coast",
    "Kent Ridge",
  ],
  "Cross Island Line": [
    "Aviation Park",
    "Loyang",
    "Pasir Ris",
    "Tampines North",
    "Defu",
    "Hougang",
    "Serangoon North",
    "Tavistock",
    "Ang Mo Kio",
    "Teck Ghee",
    "Bright Hill",
    "Turf City",
    "King Albert Park",
    "Clementi",
    "West Coast",
    "Jurong Lake District",
    "CR20 (Taman Jurong)",
    "CR21 (Jurong Pier)",
    "CR22 (Jurong Industrial Estate)",
    "CR23 (Gul Circle)",
  ],
  "Johor Bahru-Singapore RTS": ["Bukit Chagar", "Woodlands North"],
};

/**
 * Full display network: operational lines (same array references as routing)
 * plus future extensions. The map imports this; routing imports only the
 * operational subset.
 */
export const MRT_DISPLAY_LINE_STATIONS: Record<string, string[]> = {
  ...MRT_OPERATIONAL_LINE_STATIONS,
  ...MRT_FUTURE_LINE_STATIONS,
};

export const MRT_OPERATIONAL_LINE_COUNT = Object.keys(
  MRT_OPERATIONAL_LINE_STATIONS,
).length;

export const MRT_DISPLAY_LINE_COUNT = Object.keys(
  MRT_DISPLAY_LINE_STATIONS,
).length;
